listrepo update WIP

diff --git a/openvnmrj-utils/bin/listrepo b/openvnmrj-utils/bin/listrepo
--- a/openvnmrj-utils/bin/listrepo
+++ b/openvnmrj-utils/bin/listrepo
@@ -36,7 +36,7 @@ OPTIONS
     -r
       repository to use. By default "appdirs" is the repository.
     -b
-      branch to use. By default the master (stable) branch is used. 
+      branch to use. By default the master (stable) branch is used. See below.
     -p
       path to directory for repository. Default is ~/vnmrsys/openvnmrj
     -u
@@ -62,6 +62,18 @@ The -H option uses https to access GitHub; you may need to enter
 your password. 
 By default the ssh protocol is used and
 keypairs must be set up.
+
+BRANCHES
+========
+If you intend to contribute an Application Directory, 
+start a new branch for your contribution. 
+Push your new branch to your forked repository on GitHub
+then make a pull request (in GitHub) to OpenVnmrJ
+
+FORKS
+====
+See the file "forking.md" about making a fork on GitHub
+to contribute application directories to OpenVnmrJ. 
 
 %
 }
@@ -125,11 +137,11 @@ githubuser="OpenVnmrJ"
 useHTTPS=0
 verbose=0 
 repo=appdirs
-localbranch="local"
+localbranch=
 
 if [[ $? != 0 ]] ; then showhelp; exit 1 ; fi
 
-while getopts “hHr:u:p:v” option; do	
+while getopts “hHr:u:p:b:v” option; do	
   case $option in
     r)
       # repository to use, if not specified, uses appdirs
@@ -174,68 +186,48 @@ command -v git >/dev/null 2>&1 || { installgit; exit 1; }
 # ssh repo needs keypairs set up
 # specify the port because git 1.7.1 is broken and doesn't accept : ??
 if (( useHTTPS == 0 )); then
-  #repo_url="ssh://${githubuser}@192.168.2.28:22/volume1/git_repos/${repo}.git"
   repo_url="ssh://git@github.com:22/${githubuser}/${repo}.git"
-  upstream_repo_url="ssh://git@github.com:22/${githubuser}/${repo}.git"
-  #upstream_repo_url="ssh://${githubuser}@192.168.2.28:22/volume1/git_repos/${repo}.git"
+  upstream_repo_url="ssh://git@github.com:22/OpenVnmrJ/${repo}.git"
 else
   repo_url="https://github.com/${githubuser}/${repo}.git"
   upstream_repo_url="https://github.com/OpenVnmrJ/${repo}.git"
 fi
   
-if [[ ${githubuser} == "OpenVnmrJ" ]]; then
-  repodir="${ovjhome}/${repo}"
-else
-  repodir="${ovjhome}/${repo}-${localbranch}"
-fi
+repodir="${ovjhome}/${repo}"
 
 API_URL="https://api.github.com/users/${githubuser}/repos?type=owner"
-#API_URL="https://api.github.com/orgs/${githubuser}/repos?type=owner"
 repos=($(curl -s "$API_URL" | grep -Eo '"git_url": "[^"]+"' | awk '{print $2}' | awk -F"/" '{print $NF}' | sed 's/\.git"//'))
-#echo -e "${API_URL}\n"
-#printf ".%s.\n" ${repos[@]}
-#repos=( appdirs )
+
 contains "${repo}" "${repos[@]}" || { echo -e "Cannot find ${repo} in list\n${repos[@]}"; showhelp ; exit 1; }
 
-# check for git repo
+# check for git repo again
 git ls-remote "${repo_url}" >/dev/null 2>&1 || { badrepo "${repo_url}"; exit 1; }
 
-# after repo is here, we'll switch to a local branch to keep master clean
-#localbranch="local-$(uname -n)"
-
-if [[ -d "${repodir}" ]]; then
+if [[ -d "${repodir}"/.git ]]; then
   if [[ ! -w "${repodir}" ]]; then
     echo "${repodir} is not writable. Exiting."
     exit 1
   fi
-# repo probably exists already, just update
+# repo exists already, just update
   cd "${repodir}" || { echo "cd ${repodir} failed. Aborting"; exit 1; }
-  if [[ -d .git ]]; then
-    echo "Updating repository from ${repo_url}"
-    git show-ref --verify --quiet refs/heads/"${localbranch}"
-    if [[ $? == 0 ]]; then
-      git pull origin ${localbranch} || { git pull origin master; }
-    else
-      git pull origin master || { badrepo "${repo_url}"; exit 1; }
-    fi
-    git fetch --all || { echo "error in git fetch" ; exit 1; }
+  echo "Updating repository from ${repo_url}"
+  git show-ref --verify --quiet refs/heads/"${localbranch}"
+  if [[ $? == 0 ]]; then
+    git pull origin ${localbranch} || { git pull origin master; }
+  else
+    git pull origin master || { badrepo "${repo_url}"; exit 1; }
+  fi
+  git fetch --all || { echo "error in git fetch" ; exit 1; }
 # do we already have a local branch
+  if [[ ! -z ${localbranch} ]]; then
     git show-ref --verify --quiet refs/heads/"${localbranch}"
     if [[ $? == 0 ]]; then
       git checkout  ${localbranch} || { echo "error in making new branch ${localbranch}"; exit 1; }
     else
       git checkout -b ${localbranch} || { echo "error in changing to branch ${localbranch}"; exit 1; }
     fi
-  else
-# we have a directory but no repository
-    echo "Repository will be cloned into ${repodir}"
-    git clone ${repo_url} "${repodir}" . || { badrepo "${repo_url}"; exit 1; }
-    git remote add upstream ${upstream_repo_url} || { echo "error in adding upstream ${upstream_repo_url}"; exit 1; }
-    git fetch --all
-    git fetch --tags
-    git checkout -b ${localbranch} || { echo "error in making new branch ${localbranch}"; exit 1; }
   fi
-else
+else # make directory if necessary and clone
   if [[ ! -d "${ovjhome}" ]]; then
     echo "Making OpenVnmrJ directory at ${ovjhome}"
     mkdir -p "${ovjhome}" || { echo "mkdir ${ovjhome} failed. Aborting"; exit 1; }
@@ -251,7 +243,9 @@ else
   git remote add upstream ${upstream_repo_url} || { echo "error in adding upstream ${upstream_repo_url}"; exit 1; }
   git fetch --all
   git fetch --tags
-  git checkout -b ${localbranch} || { echo "error in making new branch ${localbranch}"; exit 1; }
+  if [[ ! -z ${localbranch} ]]; then
+    git checkout -b ${localbranch} || { echo "error in making new branch ${localbranch}"; exit 1; }
+  fi
 fi
 # at this point we have a repo in "${repodir}" and on the correct branch
 # All the appdirs are directories
@@ -269,12 +263,13 @@ for dir in ${appdirs}; do
   else
     title=${dir}
   fi
-  echo -e "${title}\n"  >> "${extractdir}/list"
+# echo -e "${dir}"  >> "${extractdir}/list"
+  echo -e "${title}"  > "${extractdir}/list"
 #  git --no-pager log  --pretty=format:"%b" ${tag} > ${extractdir}/${tag}
   if [[ -f "${dir}/description" ]]; then
-    cat "${dir}/description" > "${extractdir}/title"
+    cat "${dir}/description" > "${extractdir}/${title}"
   else
-    echo -e "No description for ${title}\n" > "${extractdir}/title"
+    echo -e "No description for ${title}\n" > "${extractdir}/${title}"
   fi
 done
 
