Require Apache LICENSE

diff --git a/openvnmrj-utils/bin/submitcontribution b/openvnmrj-utils/bin/submitcontribution
--- a/openvnmrj-utils/bin/submitcontribution
+++ b/openvnmrj-utils/bin/submitcontribution
@@ -61,6 +61,9 @@ pull-request to the OpenVnmrJ repository, giving the University of Oregon
 rights to use and distribute your contributions. A copy may be read at
 https://gist.github.com/ekpaulson/73530dfe735fa54d81fa
 
+You must include a file called LICENSE in your contribution and it must
+be the Apachev2 license for inclusion in the OPenVnmrJ repository.
+
 Repositories
 ============
 The repository by default is "appdirs" which contains a directory for each user
@@ -177,6 +180,8 @@ Cannot access the repository ${1}
 Check that the URL above is correct and you have correct permissions.
 If the URL starts with ssh, check this website:
 https://help.github.com/articles/generating-ssh-keys/ 
+
+Try using the -H option and an https URL
 %%
 }
 
@@ -350,7 +355,8 @@ if [[ ! -f "${dirpath}"/title ]]; then
 fi
 
 if [[ ! -f "${dirpath}"/LICENSE ]]; then
-  echo "Warning: Apache license not found within ${dirpath}"
+  echo "Error: Apache license not found within ${dirpath}"
+  exit 1
 fi
 
 # check state of directory; it is a clone of appdirs?
